from rest_framework import serializers

class BaseCustomerSerializer(serializers.Serializer):
    cust_role_id = serializers.IntegerField() # Role ID is passed in the request

class VetZoneSerializer(serializers.Serializer):

    cust_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    Village = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    total_milk_collection = serializers.CharField(max_length=255)
    total_number_MCC = serializers.CharField(max_length=255)
    vetzone_type = serializers.CharField(max_length=255)


class StockiestSerializer(serializers.Serializer):
    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    type = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    cust_name = serializers.CharField(max_length=255)
    date_of_establishment = serializers.DateField()
    gst_no = serializers.CharField(max_length=15)
    pan_no = serializers.CharField(max_length=10)
    drug_licence_no = serializers.CharField(max_length=20)
    bank_name = serializers.CharField(max_length=255)
    bank_ac_no = serializers.CharField(max_length=20)
    bank_ifsc = serializers.CharField(max_length=11)
    bank_address = serializers.CharField(max_length=255)
    anual_turnover = serializers.FloatField()
    no_of_company = serializers.IntegerField()
    area_state = serializers.CharField(max_length=255)
    area_district = serializers.CharField(max_length=255)
    expected_anual_business = serializers.FloatField()
    contact_person_name = serializers.CharField(max_length=255)
    contact_person_mobile = serializers.CharField(max_length=15)
    contact_person_email = serializers.EmailField()
    from_date = serializers.DateField(required=True)
    to_date = serializers.DateField(required=True) 

    # File uploads for KYC and other documents
    address_proof = serializers.FileField(required=False)
    firm_address_proof = serializers.FileField(required=False)
    pan_card = serializers.FileField(required=False)
    aadhar_card = serializers.FileField(required=False)
    gst_certificate = serializers.FileField(required=False)
    cancelled_check = serializers.FileField(required=False)
    photo = serializers.FileField(required=False)
    drug_licence = serializers.FileField(required=False)
    msme_certificate = serializers.FileField(required=False)


class FarmerSerializer(serializers.Serializer):
    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    cust_name = serializers.CharField(max_length=255)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    State = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    geo_tag = serializers.CharField(max_length=255)
    farmer_type = serializers.CharField(max_length=255, required=False)
    reference_from = serializers.CharField(max_length=255)

class CandFSerializer(serializers.Serializer):
    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    type = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    cust_name = serializers.CharField(max_length=255)
    date_of_establishment = serializers.DateField()
    gst_no = serializers.CharField(max_length=15)
    pan_no = serializers.CharField(max_length=10)
    drug_licence_no = serializers.CharField(max_length=20)
    bank_name = serializers.CharField(max_length=255)
    bank_ac_no = serializers.CharField(max_length=20)
    bank_ifsc = serializers.CharField(max_length=11)
    bank_address = serializers.CharField(max_length=255)
    anual_turnover = serializers.FloatField()
    no_of_company = serializers.IntegerField()
    area_state = serializers.CharField(max_length=255)
    area_district = serializers.CharField(max_length=255)
    expected_anual_business = serializers.FloatField()
    contact_person_name = serializers.CharField(max_length=255)
    contact_person_mobile = serializers.CharField(max_length=15)
    contact_person_email = serializers.EmailField()
    from_date = serializers.DateField(required=True)
    to_date = serializers.DateField(required=True) 

    # File uploads for KYC and other documents
    address_proof = serializers.FileField(required=False)
    firm_address_proof = serializers.FileField(required=False)
    pan_card = serializers.FileField(required=False)
    aadhar_card = serializers.FileField(required=False)
    gst_certificate = serializers.FileField(required=False)
    cancelled_check = serializers.FileField(required=False)
    photo = serializers.FileField(required=False)
    drug_licence = serializers.FileField(required=False)
    msme_certificate = serializers.FileField(required=False)


class KeyAccountSerializer(serializers.Serializer):
    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    type = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    cust_name = serializers.CharField(max_length=255)
    date_of_establishment = serializers.DateField()
    gst_no = serializers.CharField(max_length=15)
    pan_no = serializers.CharField(max_length=10)
    drug_licence_no = serializers.CharField(max_length=20)
    bank_name = serializers.CharField(max_length=255)
    bank_ac_no = serializers.CharField(max_length=20)
    bank_ifsc = serializers.CharField(max_length=11)
    bank_address = serializers.CharField(max_length=255)
    anual_turnover = serializers.FloatField()
    no_of_company = serializers.IntegerField()
    area_state = serializers.CharField(max_length=255)
    area_district = serializers.CharField(max_length=255)
    expected_anual_business = serializers.FloatField()
    contact_person_name = serializers.CharField(max_length=255)
    contact_person_mobile = serializers.CharField(max_length=15)
    contact_person_email = serializers.EmailField()
    from_date = serializers.DateField(required=True)
    to_date = serializers.DateField(required=True) 

    # File uploads for KYC and other documents
    address_proof = serializers.FileField(required=False)
    firm_address_proof = serializers.FileField(required=False)
    pan_card = serializers.FileField(required=False)
    aadhar_card = serializers.FileField(required=False)
    gst_certificate = serializers.FileField(required=False)
    cancelled_check = serializers.FileField(required=False)
    photo = serializers.FileField(required=False)
    drug_licence = serializers.FileField(required=False)
    msme_certificate = serializers.FileField(required=False)


class RetailerSerializer(serializers.Serializer):

    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    gst_no = serializers.CharField(max_length=15)
    drug_licence_no = serializers.CharField(max_length=20)
    anual_turnover = serializers.FloatField()

class PetshopSerializer(serializers.Serializer):

    firm_name = serializers.CharField(max_length=255)
    mob_no = serializers.CharField(max_length=15)
    email = serializers.EmailField()
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    gst_no = serializers.CharField(max_length=15)
    drug_licence_no = serializers.CharField(max_length=20)
    anual_turnover = serializers.FloatField()


class DoctorSerializer(serializers.Serializer):
    cust_name = serializers.CharField(max_length=255)
    firm_name = serializers.CharField(max_length=255)
    pet_shop_name = serializers.CharField(max_length=255)
    email = serializers.EmailField()
    education=serializers.CharField(max_length=255)
    status=serializers.CharField(max_length=255)
    type=serializers.CharField(max_length=255)
    registration_no = serializers.CharField(max_length=255)
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    gst_no = serializers.CharField(max_length=15)
    drug_licence_no = serializers.CharField(max_length=20)
    from_date = serializers.DateField(required=True)
    to_date = serializers.DateField(required=True) 
    
    address_proof = serializers.FileField(required=False)
    clinic_address_proof = serializers.FileField(required=False)
    pan_card = serializers.FileField(required=False)
    aadhar_card = serializers.FileField(required=False)
    registration_certificate = serializers.FileField(required=False)
    cancelled_check = serializers.FileField(required=False)
    photo = serializers.FileField(required=False)
    drug_licence = serializers.FileField(required=False)

class LSSSerializer(serializers.Serializer):
    cust_name = serializers.CharField(max_length=255)
    firm_name = serializers.CharField(max_length=255)
    pet_shop_name = serializers.CharField(max_length=255)
    email = serializers.EmailField()
    education=serializers.CharField(max_length=255)
    status=serializers.CharField(max_length=255)
    type=serializers.CharField(max_length=255)
    registration_no = serializers.CharField(max_length=255)
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    gst_no = serializers.CharField(max_length=15)
    drug_licence_no = serializers.CharField(max_length=20)
    from_date = serializers.DateField(required=True)
    to_date = serializers.DateField(required=True) 
    
    address_proof = serializers.FileField(required=False)
    clinic_address_proof = serializers.FileField(required=False)
    pan_card = serializers.FileField(required=False)
    aadhar_card = serializers.FileField(required=False)
    registration_certificate = serializers.FileField(required=False)
    cancelled_check = serializers.FileField(required=False)
    photo = serializers.FileField(required=False)
    drug_licence = serializers.FileField(required=False)

class PetOwnerSerializer(serializers.Serializer):

    cust_name = serializers.CharField(max_length=255)
    aadhar_card = serializers.CharField(max_length=255)
    pan_card = serializers.CharField(max_length=255)
    email = serializers.EmailField()
    mob_no = serializers.CharField(max_length=15)
    addressl1 = serializers.CharField(max_length=255)
    addressl2 = serializers.CharField(max_length=255)
    Pin_code = serializers.CharField(max_length=6)
    geo_tag = serializers.CharField(max_length=255)
    State = serializers.CharField(max_length=255)
    District = serializers.CharField(max_length=255)
    taluka = serializers.CharField(max_length=255)
    gst_no = serializers.CharField(max_length=15)
    bank_name = serializers.CharField(max_length=255)
    bank_ac_no = serializers.CharField(max_length=20)
    bank_ifsc = serializers.CharField(max_length=11)
    bank_address = serializers.CharField(max_length=255)