# Generated by Django 5.0.7 on 2024-08-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('line_manager', models.CharField(max_length=100)),
                ('permission_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminHQDiv',
            fields=[
                ('admin_hq_div_id', models.AutoField(primary_key=True, serialize=False)),
                ('hq_id', models.IntegerField()),
                ('div_id', models.IntegerField()),
                ('sub_division', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='AdminMeta',
            fields=[
                ('ad_meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('taluka', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('geo_location', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=100)),
                ('mob_number_company', models.CharField(max_length=15)),
                ('mob_number_personal', models.CharField(max_length=15)),
                ('vetzone', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
