# Generated by Django 5.0.7 on 2024-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_adminhqdiv_adminmeta_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminhqdiv',
            old_name='admin',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='adminmeta',
            old_name='admin',
            new_name='admin_id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='line_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='permission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminhqdiv',
            name='div_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminhqdiv',
            name='hq_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminhqdiv',
            name='sub_division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='emp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='geo_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='mob_number_company',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='mob_number_personal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='taluka',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminmeta',
            name='vetzone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='adminhqdiv',
            table='admin_hq_div',
        ),
        migrations.AlterModelTable(
            name='adminmeta',
            table='admin_meta',
        ),
    ]
